global:
  resolve_timeout: 5m

route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'grafana'

receivers:
- name: 'grafana'
  webhook_configs:
  - url: 'http://grafana:3000/api/alerts/test'
    http_config:
      basic_auth:
        username: 'admin'
        password: 'admin'
