# global:
#   scrape_interval: 30s
#   evaluation_interval: 10s
# rule_files:
#   - rules.yml
# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets: ["localhost:9093"]

# scrape_configs:
# - job_name: 'nextcloud'
#   scrape_interval: 90s
#   static_configs:
#     - targets: ['localhost:9205']

global:
  scrape_interval: 30s
  evaluation_interval: 10s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets: ["alertmanager:9093"]

scrape_configs:
- job_name: 'nextcloud'
  scrape_interval: 90s
  static_configs:
    - targets: ['nextcloud:9205']
- job_name: 'node'
  static_configs:
    - targets: ['node-exporter:9100']
